#!/bin/sh

I3_WALLPAPER=.config/i3/theme/wallpaper

if [ $# -ne 1 ]; then
  echo "Wrong arguments."
  exit 1
fi

if [ ! -f "$1" ]; then
  echo "wallpaper file does not exist."
  exit 1
fi

cp -f $1 $HOME/$I3_WALLPAPER
if [ $? -ne 0 ]; then
  echo "Failed to add wallpaper to WM."
  exit 1
fi

betterlockscreen -u $1 > /dev/null
if [ $? -ne 0 ]; then
  echo "Failed to add wallpaper to lock screen."
  exit 1
fi

i3-msg restart
